# Generated by Django 5.2.6 on 2025-11-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
