# Generated by Django 5.2.6 on 2025-12-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_contact_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(max_length=255),
        ),
    ]
